### ISSUE TITLE
Issues listes as WriteZStream

### ISSUE THREAD

**Issue by cnordvik** [drungrin/Fabric.Sdk.Xamarin#14]
in our iOS app almost all our issues are listed as WriteZStream as the root cause. 

But if I click an issue the top message says: 
Fatal Exception: NSInvalidArgumentException
-[WCSession activationState]: unrecognized selector sent to instance 0x14fb8270

So is there any way to get this reason surfaced as the root issue? Seems there must be something "wrong" when reporting the crash via the bindings? 

![image](https://cloud.githubusercontent.com/assets/584549/18680019/3b05d872-7f62-11e6-904e-c83b1ae0c448.png)

**Comment by drungrin** [comment]
There are 2 types of crashes, Managed and Unmanaged.

The stack trace is always the iOS native one. Unlike Android, we cannot map c# stack traces (AFIK) to native iOS ones. 
1. Click on the crash instance
2. Click on the right side button, "View All Sessions"
3. Use the switch, keys / logs
4. If it has a managed stack trace, it'll be shown on the MANAGED EXCEPTION STACK TRACE key. If this key isn't available, the exception was a pure unmanaged one.

You can enhance the crash reports, adding useful info, like this guide for Insights (this is the approach that I use, but with PostSharp instead of Fody) :

http://arteksoftware.com/xamarin-insights-unobtrusive-mobile-analytics/

Or any information that can help you to track the issue.
