### ISSUE TITLE
Unable to extract Crashlytics build info from the dropped APK

### ISSUE THREAD

**Issue by henningms** [drungrin/Fabric.Sdk.Xamarin#5]
Hi,

Was looking into using this for a project but when I try to upload the APK with the Fabric plugin for Android Studio it complains that it can't extract the Crashlytics build info from the APK:

"Unable to extract Crashlytics build info from the dropped APK. Please make sure your Crashlytics build tool plugin is installed and enabled"

Anyone had this problem?

**Comment by drungrin** [comment]
For crashlytics on android, there is a hidden configuration, you need to add/update the build id using a string resource

<code>&lt;string name="com.crashlytics.android.build_id">e9e6beb9c4284289ac68b9ab76a9ee56&lt;/string></code>

**Comment by henningms** [comment]
Yeah I did that but still no go :S

**Comment by drungrin** [comment]
Make a sample so I can build and check. That build info error is because of misconfiguration.

Make sure that you first do the on boarding process on android studio first, enable the kits for a empty application with the same id, run it so it appears on crashlytics / answers dashboard.

Does my sample work changing the build id on

https://github.com/drungrin/Fabric.Sdk.Xamarin/blob/master/Samples/FormsSample/Droid/Resources/values/strings.xml

and appkey on:

https://github.com/drungrin/Fabric.Sdk.Xamarin/blob/master/Samples/FormsSample/Droid/Properties/AndroidManifest.xml

to your own?

**Comment by henningms** [comment]
Nope, that doesn't work. Tried changing the package name to match. Hmm.

**Comment by henningms** [comment]
Invited you to a repo now with the full project as is. It's not a big project
