### ISSUE TITLE
Dropping .apk in Android Studio plugin for Beta distribution issue

### ISSUE THREAD

**Issue by Tomsons** [drungrin/Fabric.Sdk.Xamarin#7]
Hello,

just followed your instructions step by step. Everything's working as expected, Crashlytics issue reporting works as expected. The only issue I'm getting is the following:

When I try to drop the generated .apk into the Android Studio Fabric plugin in order to distribute it through Beta I'm getting this error:

> Unable to extract Crashlytics build info from the dropped APK. Please make sure your Crashlytics build tool plugin is installed and enabled.

As I don't get any kind of logs, do you may have any clue how to solve this issue?

**Comment by Tomsons** [comment]
OK Just got it. For those who are getting stuck on it. After several hours, just found out what I have to do in order to distribute the app through Android Studio Fabric Plugin.

You'll have to copy the `assets/crashlytics-build.properties` file generated within your native helper application skeleton and paste it into the `Assets` folder of your Xamarin project. Don't forget to mark this file as `AndroidAsset` in its build actions.

Create your archive for distribution and simply drop your brand new generated apk into Android Studio and that's it.

GL & HF

**Comment by drungrin** [comment]
Thanks for sharing the solution.

I didn't used Beta, Good to know that it also works.

I'll include that gotcha on the readme.

**Comment by brittonbeckham** [comment]
FYI everyone, on this I just found out the hard way that for each new beta build you must do a series of tasks:

1) Go to Android Studio, update the build version name and version code in the project settings
2) Build project in Android Studio 
3) A new `crashlytics-build.properties` file will be generated in your android project with unique buid_id
4) Copy the contents of this file and overwrite the one in your Xamarin.Forms Android project
5) Rebuild your solution in Visual Studio (in Release)
6) Export `.apk`
7) Drag the newly generated `.apk` back into the Fabric.io plugin in Android Studio

**Comment by franckbrun** [comment]
Hi all,
The "Fabric Ant build tools" contains a jar file **crashlytics-devtools.jar** which can be used in a script to generate all crahslytics files "crashlytics-build.properties" and the special xml file in res/values.

Then you can use **fastlane** to submit the signed-zipaligned APK file. No need to use Android studio anymore.

Just one problem for me now (I don't think it is linked with this solution) but even the submitted APK is signed and zipaligned, the APK downloaded by the "Beta Crachlytics App" can be installed but not launched because all the Dll files in the "assemblies" folder are not zipaligned anymore.
The same problem appear with the "Android Studio Drop APK" solution.
Has anybody  this problem ?

**Comment by jkells** [comment]
Hi @franckbrun did you make any progress on this? I'm seeing the zipalign problem now too.

**Comment by chouhanv** [comment]
I have not found crashlytics-build.properties in my android studio app.
Please Help me.

**Comment by vigoou** [comment]
@Tomsons thanks for this solution.
